//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeHubRuntime) DeepCopyInto(out *CodeHubRuntime) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeHubRuntime.
func (in *CodeHubRuntime) DeepCopy() *CodeHubRuntime {
	if in == nil {
		return nil
	}
	out := new(CodeHubRuntime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CodeHubRuntime) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeHubRuntimeList) DeepCopyInto(out *CodeHubRuntimeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		inItems, outItems := &in.Items, &out.Items
		*outItems = make([]CodeHubRuntime, len(*inItems))
		for i := range *inItems {
			(*inItems)[i].DeepCopyInto(&(*outItems)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeHubRuntimeList.
func (in *CodeHubRuntimeList) DeepCopy() *CodeHubRuntimeList {
	if in == nil {
		return nil
	}
	out := new(CodeHubRuntimeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CodeHubRuntimeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeHubRuntimeSpec) DeepCopyInto(out *CodeHubRuntimeSpec) {
	*out = *in
	if in.Env != nil {
		inEnv, outEnv := &in.Env, &out.Env
		*outEnv = make(map[string]string, len(*inEnv))
		for key, val := range *inEnv {
			(*outEnv)[key] = val
		}
	}
	if in.Resources != nil {
		inR, outR := &in.Resources, &out.Resources
		*outR = new(corev1.ResourceRequirements)
		(*inR).DeepCopyInto(*outR)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeHubRuntimeSpec.
func (in *CodeHubRuntimeSpec) DeepCopy() *CodeHubRuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(CodeHubRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeHubRuntimeStatus) DeepCopyInto(out *CodeHubRuntimeStatus) {
	*out = *in
	in.LastEvaluatedTime.DeepCopyInto(&out.LastEvaluatedTime)
	if in.IdleSince != nil {
		inT, outT := &in.IdleSince, &out.IdleSince
		*outT = (*inT).DeepCopy()
	}
	if in.Conditions != nil {
		inC, outC := &in.Conditions, &out.Conditions
		*outC = make([]metav1.Condition, len(*inC))
		for i := range *inC {
			(*inC)[i].DeepCopyInto(&(*outC)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeHubRuntimeStatus.
func (in *CodeHubRuntimeStatus) DeepCopy() *CodeHubRuntimeStatus {
	if in == nil {
		return nil
	}
	out := new(CodeHubRuntimeStatus)
	in.DeepCopyInto(out)
	return out
}
